### ISSUE TITLE
Automatically getting authentication info

### ISSUE THREAD

**Issue by WasabiFan** [waltfy/destiny#10]
In the readme, it says:
> TODO: Working on automating this, for now simply inspect your resources to find cookies. Guides can be found online.

I'm wondering if you made any progress on this. I have written an app (using this library in combination with some of my own query logic) that would benefit greatly from being able to automatically get the cookie and auth info.

Any progress or insights would be appreciated!

**Comment by waltfy** [comment]
@WasabiFan it is a bit tough to do this. I will have a think about it — so sorry it has taken so long to respond to this issue. You should hear back soon.

**Comment by waltfy** [comment]
@WasabiFan Bungie has made API keys necessary, always. You can get one at https://www.bungie.net/developer.

FYI https://github.com/waltfy/destiny/pull/12
