### ISSUE TITLE
Need to include X-API-Key header in all requests, not sure how

### ISSUE THREAD

**Issue by Kinsbane** [waltfy/destiny#11]
Hi,

Since the release of 2.0 / The Taken King, and because of items deemed "Classified" by Bungie in the Armory, all requests now require the X-API-Key header.

I cannot seem to get my requests to send the X-API-Key header. I had thought I can pass an object with the Destiny Client's .Search method, or .Account method, and nothing works.

Then I thought I could modify destiny.js directly to have X-API-Key in the headers at all times, but this was no go because I'm unfamiliar with how the Destiny Client module is put together. 

I would just need to know how I can have every request have the X-API-Key header to start updating my app. Thanks in advance for any help!

**Comment by waltfy** [comment]
@Kinsbane I see, thanks for pointing that out. You seem to be correct, any requests missing the `X-API-Key` header seems to return:

```js
{
  ErrorCode: 2102,
  ThrottleSeconds: 0,
  ErrorStatus: 'ApiKeyMissingFromRequest',
  Message: 'Please add valid X-API-Key header to request.  Visit https://www.bungie.net/developer for details.',
  MessageData: {}
}
```

It seems that there was also a bug in the library itself, where headers passed in were being completely ignored.

On `v0.5.0` you have to  initialise the client with an `apiKey`, which is the first argument to the client constructor.

```js
var destiny = require('./index')(process.env.BUNGIE_API_KEY); // replace it with your key
```
