### ISSUE TITLE
CORS issue with some endpoints

### ISSUE THREAD

**Issue by akilham** [waltfy/destiny#13]
Hey!

Thanks for the tool - I've only just started using it but it's going to be super helpful.

I was able to use the Search method fine, but trying the Account method I received this error:

Fetch API cannot load http://localhost:1337/www.bungie.net/platform/Destiny/2/Account/4611686018450401470/Character/2305843009326474174/Activities. The request was redirected to 'http://www.bungie.net/platform/Destiny/2/Account/4611686018450401470/Character/2305843009326474174/Activities/', which is disallowed for cross-origin requests that require preflight.

I was using Javascript from my browser with your proxy.js script, but I tried cors-proxy from npm just in case it was the proxy server and it still wasn't working.

I noticed that some of the endpoints (the ones that weren't working) do not have a trailing / on them. I added a slash on to the endpoints on line 13765 of destiny.js and it fixed my problem.

I don't know how to do a pull request so hopefully you can verify this and make the changes in the code.

**Comment by waltfy** [comment]
@akilham thanks for reporting this issue, well spotted — should be fixed as of https://github.com/waltfy/destiny/releases/tag/v0.5.2.
