### ISSUE TITLE
try to request Account info but failed

### ISSUE THREAD

**Issue by nguyennk** [waltfy/destiny#4]
error:
XMLHttpRequest cannot load http://www.bungie.net/Platform/Destiny/TigerPSN/Account/4611686018429528212/. The 'Access-Control-Allow-Origin' header has a value 'http://www.bungie.net' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.

**Comment by waltfy** [comment]
Have you got the proxy server running?

**Comment by nguyennk** [comment]
Yes, I got the search function running, i think Destiny.main is running too
Only the Destiny.account got the problem

(Tried both request using just proxy and your destiny.js request)

**Comment by waltfy** [comment]
Will investigate soon.

**Comment by waltfy** [comment]
@nguyennk are you still having problems?

**Comment by waltfy** [comment]
I cannot reproduce this in any way.

**Comment by jtschopp** [comment]
Sorry for late reply, I actually just give up on this and write my own connector already XD thanks for your effort anyway :)

**Comment by nguyennk** [comment]
Sorry for late reply, I actually give up on this already and write my own
connector for the api already ^^ thanks for your effort anyway :)

On Wed, May 27, 2015 at 4:33 PM, Walter Carvalho <notifications@github.com>
wrote:

> I cannot reproduce this in any way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waltfy/destiny/issues/4#issuecomment-106065168>.
>



-- 


*Software** Developer*

*The Normandy Group LLC*.  |  Visit Our Website
<http://www.thenormandygroup.com/>

Office:   855. Team. TNG

Mobile:  513.593.4021

5151 Pfeiffer Road  ∙ Suite 210 | Cincinnati, Ohio 45242
