### ISSUE TITLE
Can you provide an example of how to use the response from a query

### ISSUE THREAD

**Issue by TheHandsomeCoder** [waltfy/destiny#5]
I was trying to get a better idea of the returned object but there is no examples that I can find, could you show an example of how you use the response?

**Comment by waltfy** [comment]
If you hit that URL, you should get a response. 
http://www.bungie.net/Platform/Destiny/1/Account/4611686018439937004/

**Pro tip:** Not sure if you already have it, but installing something like [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) will help you analyse the response.

Hope this helps.
